# Generated by Django 4.2.30 on 2026-05-26 01:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('national_id', models.CharField(blank=True, max_length=20, verbose_name='رقم الهوية')),
                ('is_approved', models.BooleanField(default=False, verbose_name='معتمد من الإدارة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات الإدارة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owner_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'مالك عقار',
                'verbose_name_plural': 'ملاك العقارات',
            },
        ),
    ]
