# Generated by Django 4.2.30 on 2026-05-30 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_property_owner_property_rejection_reason_and_more'),
        ('owners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerAccountingEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='تاريخ الحجز')),
                ('end_date', models.DateField(verbose_name='تاريخ انتهاء الحجز')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='السعر / الإيراد')),
                ('expenses', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='المصروفات')),
                ('debts', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='الديون')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='المبلغ المدفوع')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounting_entries', to='owners.ownerprofile', verbose_name='المالك')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounting_entries', to='properties.property', verbose_name='رقم الشقة')),
            ],
            options={
                'verbose_name': 'حساب مالك',
                'verbose_name_plural': 'حسابات الملاك',
                'ordering': ['-start_date', '-created_at'],
            },
        ),
    ]
