# Generated by Django 4.2.30 on 2026-05-30 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0002_owneraccountingentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='اسم الحساب')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='owners.ownerprofile', verbose_name='المالك')),
            ],
            options={
                'verbose_name': 'حساب مالك',
                'verbose_name_plural': 'حسابات الملاك',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OwnerDebt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creditor_name', models.CharField(max_length=150, verbose_name='اسم الدائن')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='الإجمالي')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='المدفوع')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debts', to='owners.owneraccount', verbose_name='الحساب')),
            ],
            options={
                'verbose_name': 'دين',
                'verbose_name_plural': 'الديون',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OwnerExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المبلغ')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('description', models.CharField(max_length=255, verbose_name='البيان')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='owners.owneraccount', verbose_name='الحساب')),
            ],
            options={
                'verbose_name': 'مصروف',
                'verbose_name_plural': 'المصروفات',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OwnerRevenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المبلغ')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('description', models.CharField(max_length=255, verbose_name='البيان')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenues', to='owners.owneraccount', verbose_name='الحساب')),
            ],
            options={
                'verbose_name': 'إيراد',
                'verbose_name_plural': 'الإيرادات',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='OwnerAccountingEntry',
        ),
    ]
