# Generated by Django 4.2.30 on 2026-05-02 02:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0002_property_owner_name_property_owner_phone'),
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='العنوان')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='المبلغ')),
                ('payment_method', models.CharField(choices=[('cash', 'كاش'), ('instapay', 'إنستاباي'), ('vodafone', 'فودافون'), ('bank', 'بنك')], max_length=20, verbose_name='طريقة الاستلام')),
                ('category', models.CharField(choices=[('rent', 'إيجار'), ('sale', 'بيع عقار'), ('freelance', 'عمل حر'), ('gift', 'هدية'), ('other', 'أخرى')], max_length=20, verbose_name='التصنيف')),
                ('source', models.CharField(blank=True, help_text='مثال: حجز BLT-ED2E54', max_length=255, null=True, verbose_name='المصدر')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('note', models.TextField(blank=True, null=True, verbose_name='ملاحظة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookings.booking', verbose_name='مرتبط بحجز')),
            ],
            options={
                'verbose_name': 'دخل',
                'verbose_name_plural': 'الدخل',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='العنوان')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='المبلغ')),
                ('payment_method', models.CharField(choices=[('cash', 'كاش'), ('instapay', 'إنستاباي'), ('vodafone', 'فودافون'), ('bank', 'بنك')], max_length=20, verbose_name='طريقة الدفع')),
                ('category', models.CharField(choices=[('personal', 'شخصي'), ('business', 'بزنس'), ('maint', 'صيانة'), ('marketing', 'تسويق'), ('bills', 'فواتير'), ('food', 'أكل'), ('transport', 'مواصلات'), ('other', 'أخرى')], max_length=20, verbose_name='التصنيف')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='receipts/', verbose_name='صورة الإيصال')),
                ('note', models.TextField(blank=True, null=True, verbose_name='ملاحظة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookings.booking', verbose_name='مرتبط بحجز')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.property', verbose_name='مرتبط بعقار')),
            ],
            options={
                'verbose_name': 'مصروف',
                'verbose_name_plural': 'المصاريف',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
