# Generated by Django 4.2.30 on 2026-05-02 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='receipt_image',
            field=models.FileField(blank=True, help_text='يمكنك رفع صور أو ملفات PDF', null=True, upload_to='receipts/', verbose_name='صورة الإيصال'),
        ),
    ]
