# Generated by Django 6.0.4 on 2026-04-12 15:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='العنوان')),
                ('beach', models.CharField(choices=[('fanar', 'الفنار'), ('narges', 'النرجس'), ('zahraa', 'الزهراء'), ('salam', 'السلام'), ('amal', 'الأمل'), ('fayruz', 'الفيروز')], max_length=20, verbose_name='الشاطئ')),
                ('type', models.CharField(choices=[('شقة', 'شقة'), ('شاليه', 'شاليه'), ('استوديو', 'استوديو'), ('فيلا', 'فيلا'), ('بنتهاوس', 'بنتهاوس')], max_length=20, verbose_name='نوع العقار')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('price_daily', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='السعر اليومي (ج)')),
                ('price_monthly', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='السعر الشهري (ج)')),
                ('price_sale', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='سعر البيع (ج)')),
                ('rooms', models.PositiveSmallIntegerField(verbose_name='عدد الغرف')),
                ('area', models.PositiveIntegerField(verbose_name='المساحة (م²)')),
                ('floor', models.SmallIntegerField(default=1, verbose_name='رقم الدور')),
                ('distance_to_sea', models.PositiveIntegerField(verbose_name='المسافة من البحر (م)')),
                ('rating', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='التقييم')),
                ('reviews', models.PositiveIntegerField(default=0, verbose_name='عدد التقييمات')),
                ('is_popular', models.BooleanField(default=False, verbose_name='الأكثر طلبًا')),
                ('is_special_offer', models.BooleanField(default=False, verbose_name='عرض خاص')),
                ('available', models.BooleanField(default=True, verbose_name='متاح')),
                ('amenities', models.TextField(blank=True, default='', help_text='مفصولة بفاصلة: wifi,ac,sea_view', verbose_name='المميزات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'عقار',
                'verbose_name_plural': 'العقارات',
                'ordering': ['-is_popular', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='properties/', verbose_name='الصورة')),
                ('is_main', models.BooleanField(default=False, verbose_name='صورة رئيسية')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='الترتيب')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property', verbose_name='العقار')),
            ],
            options={
                'verbose_name': 'صورة عقار',
                'verbose_name_plural': 'صور العقارات',
                'ordering': ['order', 'id'],
            },
        ),
    ]
