# Generated by Django 4.2.30 on 2026-05-02 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='owner_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='اسم صاحب العقار'),
        ),
        migrations.AddField(
            model_name='property',
            name='owner_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم صاحب العقار'),
        ),
    ]
