# Generated by Django 4.2.30 on 2026-05-02 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_property_owner_name_property_owner_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyimage',
            name='image',
            field=models.FileField(help_text='يمكنك رفع أي نوع من الصور (JPG, PNG, HEIC, إلخ)', upload_to='properties/', verbose_name='الصورة'),
        ),
    ]
