# Generated by Django 4.2.30 on 2026-05-04 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_alter_propertyimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='price_note',
            field=models.CharField(blank=True, default='الأسعار تختلف حسب اليوم — سنتواصل معك', max_length=255, verbose_name='ملاحظة السعر'),
        ),
        migrations.AlterField(
            model_name='property',
            name='price_daily',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='سعر استرشادي يومي (ج)'),
        ),
        migrations.AlterField(
            model_name='property',
            name='price_monthly',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='سعر استرشادي شهري (ج)'),
        ),
        migrations.AlterField(
            model_name='property',
            name='price_sale',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='سعر بيع استرشادي (ج)'),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='image',
            field=models.FileField(help_text='يدعم الصور من الهاتف مباشرة', upload_to='properties/', verbose_name='الصورة'),
        ),
    ]
