# Generated by Django 4.2.30 on 2026-05-14 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_property_price_note_alter_property_price_daily_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='أيقونة الميزة (Material Icon)')),
                ('label', models.CharField(max_length=100, verbose_name='اسم الميزة بالعربي')),
            ],
            options={
                'verbose_name': 'ميزة',
                'verbose_name_plural': 'المميزات',
            },
        ),
        migrations.RemoveField(
            model_name='property',
            name='amenities',
        ),
        migrations.AddField(
            model_name='property',
            name='amenities',
            field=models.ManyToManyField(blank=True, to='properties.amenity', verbose_name='المميزات'),
        ),
    ]
