# Generated by Django 4.2.30 on 2026-05-22 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_amenity_remove_property_amenities_property_amenities'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم المدينة')),
                ('slug', models.SlugField(max_length=60, unique=True, verbose_name='الـ Slug')),
                ('region', models.CharField(blank=True, max_length=100, verbose_name='المنطقة')),
                ('description', models.TextField(blank=True, verbose_name='وصف')),
                ('icon', models.CharField(default='🏖️', max_length=10, verbose_name='أيقونة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشطة')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='الترتيب')),
            ],
            options={
                'verbose_name': 'مدينة',
                'verbose_name_plural': 'المدن',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Beach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الشاطئ')),
                ('slug', models.SlugField(max_length=60, verbose_name='الـ Slug')),
                ('icon', models.CharField(default='🏖️', max_length=10, verbose_name='أيقونة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='الترتيب')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beaches', to='properties.city', verbose_name='المدينة')),
            ],
            options={
                'verbose_name': 'شاطئ',
                'verbose_name_plural': 'الشواطئ',
                'ordering': ['order', 'name'],
                'unique_together': {('city', 'slug')},
            },
        ),
        migrations.AddField(
            model_name='property',
            name='beach_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='properties.beach', verbose_name='الشاطئ'),
        ),
    ]
