# Generated by Django 4.2.30 on 2026-05-22 08:49

from django.db import migrations


def seed_cities_and_beaches(apps, schema_editor):
    City     = apps.get_model('properties', 'City')
    Beach    = apps.get_model('properties', 'Beach')
    Property = apps.get_model('properties', 'Property')

    # ── Create Cities ──────────────────────────
    baltim = City.objects.create(
        name='مصيف بلطيم',
        slug='baltim',
        region='كفر الشيخ',
        icon='🌊',
        order=1
    )

    marina_delta = City.objects.create(
        name='مارينا دلتا',
        slug='marina-delta',
        region='كفر الشيخ',
        icon='⛵',
        order=2
    )

    marina_lagoons = City.objects.create(
        name='مارينا لاجونز',
        slug='marina-lagoons',
        region='كفر الشيخ',
        icon='🚤',
        order=3
    )

    farma = City.objects.create(
        name='فارما بيتش',
        slug='farma-beach',
        region='كفر الشيخ',
        icon='🏖️',
        order=4
    )

    ola = City.objects.create(
        name='ولا',
        slug='ola',
        region='كفر الشيخ',
        icon='🌅',
        order=5
    )

    # ── Create Baltim beaches ──────────────────
    beach_map = {}

    baltim_beaches = [
        ('fanar',  'الفنار',  '🏖️', 1),
        ('narges', 'النرجس', '🌊', 2),
        ('zahraa', 'الزهراء', '⛱️', 3),
        ('salam',  'السلام', '🌅', 4),
        ('amal',   'الأمل',  '🏝️', 5),
        ('fayruz', 'الفيروز','💎', 6),
    ]

    for slug, name, icon, order in baltim_beaches:
        b = Beach.objects.create(
            city=baltim,
            name=name,
            slug=slug,
            icon=icon,
            order=order
        )
        beach_map[slug] = b

    # ── Single-beach cities ────────────────────
    Beach.objects.create(
        city=marina_delta,
        name='مارينا دلتا',
        slug='marina-delta',
        icon='⛵',
        order=1
    )

    Beach.objects.create(
        city=marina_lagoons,
        name='مارينا لاجونز',
        slug='marina-lagoons',
        icon='🚤',
        order=1
    )

    Beach.objects.create(
        city=farma,
        name='فارما بيتش',
        slug='farma-beach',
        icon='🏖️',
        order=1
    )

    Beach.objects.create(
        city=ola,
        name='ولا',
        slug='ola',
        icon='🌅',
        order=1
    )

    # ── Link existing Properties to Beach ──────
    for prop in Property.objects.all():
        old_beach = prop.beach

        if old_beach in beach_map:
            prop.beach_new = beach_map[old_beach]
            prop.save()

class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_city_beach_property_beach_new'),
    ]

    operations = [
        migrations.RunPython(seed_cities_and_beaches),
    ]
