# Generated by Django 4.2.30 on 2026-05-22 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_seed_cities_beaches'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='beach',
            field=models.CharField(blank=True, choices=[('fanar', 'الفنار'), ('narges', 'النرجس'), ('zahraa', 'الزهراء'), ('salam', 'السلام'), ('amal', 'الأمل'), ('fayruz', 'الفيروز')], max_length=20, null=True, verbose_name='الشاطئ (القديم)'),
        ),
    ]
