# Generated by Django 4.2.30 on 2026-05-30 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_property_owner_property_rejection_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='video_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='رابط فيديو للعقار'),
        ),
    ]
