# Generated by Django 4.2.30 on 2026-06-03 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0010_property_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='properties/', verbose_name='الصورة الرئيسية'),
        ),
    ]
