# Generated by Django 4.2.30 on 2026-06-13 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0011_property_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='offer_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='سعر العرض (بعد الخصم)'),
        ),
        migrations.AddField(
            model_name='property',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='السعر الأصلي (قبل الخصم)'),
        ),
    ]
