# Generated by Django 4.2.30 on 2026-06-19 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0012_offer_price_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyimage',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='properties/thumbs/', verbose_name='صورة مصغّرة'),
        ),
    ]
