# Generated by Django 6.0.4 on 2026-04-12 15:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم المطعم')),
                ('address', models.TextField(blank=True, verbose_name='العنوان')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='الهاتف')),
                ('pin_hash', models.CharField(help_text='لا تعدل هذا الحقل يدوياً — استخدم زر تغيير الـ PIN', max_length=64, verbose_name='PIN مشفّر')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('commission_rate', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='نسبة العمولة (%)')),
                ('subscription_type', models.CharField(choices=[('free', 'مجاني'), ('basic', 'أساسي'), ('premium', 'مميز')], default='free', max_length=10, verbose_name='نوع الاشتراك')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'مطعم شريك',
                'verbose_name_plural': 'المطاعم الشريكة',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=200, verbose_name='اسم المستأجر')),
                ('guest_phone', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('guest_email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('guest_notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('booking_type', models.CharField(choices=[('daily', 'يومي'), ('monthly', 'شهري'), ('sale', 'بيع')], default='daily', max_length=10, verbose_name='نوع الحجز')),
                ('check_in', models.DateField(verbose_name='تاريخ الوصول')),
                ('check_out', models.DateField(verbose_name='تاريخ المغادرة')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='إجمالي الإيجار')),
                ('service_fee', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='رسوم الخدمة')),
                ('grand_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الإجمالي الكلي')),
                ('payment_method', models.CharField(choices=[('cash', 'دفع نقدي'), ('vodafone', 'فودافون كاش'), ('bank', 'تحويل بنكي')], default='cash', max_length=20, verbose_name='طريقة الدفع')),
                ('status', models.CharField(choices=[('pending', 'في الانتظار'), ('confirmed', 'مؤكد'), ('cancelled', 'ملغي'), ('completed', 'مكتمل')], default='pending', max_length=20, verbose_name='الحالة')),
                ('booking_ref', models.CharField(blank=True, max_length=20, unique=True, verbose_name='رقم الحجز')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='properties.property', verbose_name='العقار')),
            ],
            options={
                'verbose_name': 'حجز',
                'verbose_name_plural': 'الحجوزات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScanAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_uuid', models.UUIDField(db_index=True, verbose_name='UUID الفاوتشر')),
                ('status', models.CharField(choices=[('valid', 'صالح'), ('used', 'مستخدم مسبقاً'), ('expired', 'منتهي الصلاحية'), ('invalid_sig', 'توقيع غير صحيح'), ('locked', 'مقفول مؤقتاً'), ('invalid_pin', 'PIN خاطئ'), ('not_allowed', 'مطعم غير مصرح'), ('confirmed', 'تم التأكيد')], max_length=20, verbose_name='النتيجة')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('details', models.TextField(blank=True, verbose_name='تفاصيل')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'محاولة scan',
                'verbose_name_plural': 'محاولات الـ Scan',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['voucher_uuid', 'created_at'], name='bookings_sc_voucher_441efc_idx'), models.Index(fields=['ip_address', 'created_at'], name='bookings_sc_ip_addr_0b9273_idx')],
            },
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='كود الفاوتشر')),
                ('hmac_signature', models.CharField(blank=True, max_length=128, verbose_name='HMAC signature')),
                ('discount_percentage', models.IntegerField(choices=[(5, '5%'), (10, '10%'), (15, '15%'), (20, '20%')], default=10, verbose_name='نسبة الخصم')),
                ('usage_limit', models.PositiveSmallIntegerField(default=1, verbose_name='عدد مرات الاستخدام المسموح')),
                ('times_used', models.PositiveSmallIntegerField(default=0, verbose_name='عدد مرات الاستخدام الفعلي')),
                ('expires_at', models.DateField(db_index=True, verbose_name='تاريخ انتهاء الصلاحية')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعّل')),
                ('locked_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت القفل')),
                ('locked_session', models.CharField(blank=True, max_length=64, verbose_name='session القفل')),
                ('action_token', models.CharField(blank=True, max_length=64, verbose_name='action token')),
                ('action_token_expires', models.DateTimeField(blank=True, null=True, verbose_name='انتهاء الـ action token')),
                ('qr_code', models.ImageField(blank=True, upload_to='vouchers/qr/', verbose_name='صورة QR Code')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('allowed_restaurants', models.ManyToManyField(blank=True, help_text='اتركه فارغاً للسماح بكل المطاعم', related_name='vouchers', to='bookings.restaurant', verbose_name='المطاعم المسموح بها')),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='voucher', to='bookings.booking', verbose_name='الحجز')),
            ],
            options={
                'verbose_name': 'فاوتشر',
                'verbose_name_plural': 'الفاوتشرات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VoucherRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name_manual', models.CharField(blank=True, max_length=200, verbose_name='اسم المطعم (يدوي)')),
                ('invoice_image', models.ImageField(upload_to='vouchers/invoices/%Y/%m/', verbose_name='صورة الفاتورة')),
                ('original_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ الأصلي (ج)')),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قيمة الخصم (ج)')),
                ('final_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ بعد الخصم (ج)')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('redeemed_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='وقت الاسترداد')),
                ('restaurant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redemptions', to='bookings.restaurant', verbose_name='المطعم')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='bookings.voucher', verbose_name='الفاوتشر')),
            ],
            options={
                'verbose_name': 'عملية استرداد',
                'verbose_name_plural': 'عمليات الاسترداد',
                'ordering': ['-redeemed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['uuid'], name='bookings_vo_uuid_a1e30e_idx'),
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['expires_at', 'times_used'], name='bookings_vo_expires_962777_idx'),
        ),
    ]
