# Generated by Django 4.2.30 on 2026-05-02 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='المبلغ المدفوع'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='grand_total',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الإجمالي الكلي (المطلوب)'),
        ),
    ]
