# Generated by Django 4.2.30 on 2026-05-04 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_amount_paid_alter_booking_grand_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='agreed_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='السعر المتفق عليه (يُحدد لاحقًا)'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='grand_total',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True, verbose_name='الإجمالي الكلي (المطلوب)'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='service_fee',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True, verbose_name='رسوم الخدمة'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending_contact', 'في انتظار التواصل'), ('contacted', 'تم التواصل'), ('price_agreed', 'تم الاتفاق على السعر'), ('confirmed', 'مؤكد'), ('cancelled', 'ملغي'), ('completed', 'مكتمل')], default='pending_contact', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True, verbose_name='إجمالي الإيجار'),
        ),
    ]
