# Generated by Django 4.2.30 on 2026-05-16 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_agreed_price_alter_booking_grand_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='guest_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني'),
        ),
    ]
